"""Datos del proyecto (fuente única para la app, los instaladores y el README)."""
NOMBRE = "OweeStudent"
VERSION = "0.2.1"
AUTOR = "Hector Martinez"
WEB = "https://www.oweeme.com"
EMAIL = "hector@oweeme.com"
DONACIONES = "https://www.paypal.com/paypalme/oweeandme"
